server:
  port: 65378

spring:
  application:
    name: service-consumer-movie
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:65377/eureka/
  instance:
    hostname: service-consumer-movie